name = "CyberAlchemy"
version = "0.1.0"
keywords = ["math", "algebra", "non-associative", "cybernetics", "physics"]
defaultTargets = ["LaRueProtorealAlgebra", "InfoPhysAxioms"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"

[[lean_lib]]
name = "LaRueProtorealAlgebra"

[[lean_lib]]
name = "InfoPhysAxioms"
